rottenpotatoes-rails-intro/config/routes.rb
Rails.application.routes.draw do

  root 'movies#index', as: :home

  resources :movies
  

end

rottenpotatoes-rails-intro/app/models/movie.rb
class Movie < ActiveRecord::Base
end

rottenpotatoes-rails-intro/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rottenpotatoes-rails-intro/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  helper_method :sort_column, :sort_dir

  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :release_date)
  end

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    if session[:column]==nil or (session[:column] != sort_column and params[:column]!=nil)
      session[:column] = sort_column
    end
    if session[:dir]==nil or (session[:dir] != sort_dir and params[:dir]!=nil)
      session[:dir] = sort_dir
    end
    if session[:ratings].blank? or params[:commit]!=nil
      session[:ratings] = boxes_checked
    end
    
    @all_ratings = Movie.select("DISTINCT rating").map(&:rating)
    @checked = session[:ratings]
    if session[:dir] != ""
      if @checked.empty?
        @movies = Movie.order("#{session[:column]} #{session[:dir]}").all
      else
        @movies = Movie.order("#{session[:column]} #{session[:dir]}").select {|i| @checked.include?(i.rating)? true: false}
      end
      if session[:column] == "title"
        @val = "hilite"
        @val2 = ""
      else
        @val = ""
        @val2 = "hilite"
      end
    else
      if @checked.empty?
        @movies = Movie.all
      else 
        @movies = Movie.all.select{|i| @checked.include?(i.rating)? true: false}
      end
      @val = ""
      @val2 = ""
    end
  end
  
  private def boxes_checked
    if params[:ratings] == nil
      return []
    end
    return params[:ratings].keys
  end
  
  def sort_column
    if params[:column] == "Movie Title"
      return "title"
    elsif params[:column] == "Release Date"
      return "release_date"
    else
      return "title"
    end
  end
  
  def sort_dir
    if params[:dir] == "asc"
      return "asc"
    elsif params[:dir] == "desc"
      return "desc"
    else
      return ""
    end
  end
  
  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end
  
  

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

end

rottenpotatoes-rails-intro/app/helpers/application_helper.rb
module ApplicationHelper
end

rottenpotatoes-rails-intro/app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
  
  def sort_hyperlink(column)
    column2 = (column == "Movie Title")? "title":"release_date"
    dir = (column2 == sort_column && sort_dir == "asc")? "desc":"asc"
    ident = ""
    if column2 == "title"
      ident = "title_header"
    else
      ident = "release_date_header"
    end
    link_to "#{column.titleize}",{column: column, dir: dir}, :id => ident
  end
end

rottenpotatoes-rails-intro/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

rottenpotatoes-rails-intro/app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

rottenpotatoes-rails-intro/app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

= form_tag home_path ,:id => "ratings_form", :method => :get do
  Include:
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]",1,@checked.include?(rating)?true:false, :id => "ratings_#{rating}"
  = submit_tag 'Refresh', :id => "ratings_submit"

%table#movies
  %thead
    %tr
      %th{:class => @val}= sort_hyperlink "Movie Title"
      %th Rating
      %th{:class => @val2}= sort_hyperlink "Release Date"
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

-# Disclaimer
-# Design pattern followed from https://richonrails.com/articles/sortable-table-columns

rottenpotatoes-rails-intro/app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

rottenpotatoes-rails-intro/app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path